Merge changes from topic 'aosp-commits' into n7.1
* changes:
  sensors: fix native crash when dynamic sensor is removed
  sensors: intern jstrings for memory savings
  NullPointerException: Attempt to invoke virtual method 'int android.os.Parcel.dataSize()' on a null object reference

Change-Id: I7159d5c8e781e9988922064008637b54e9bb8bf6